// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'layout': string;
  'layout__main': string;
  'layout__menu': string;
}
export const cssExports: CssExports
export default cssExports
